# Generated by Django 5.2.5 on 2025-08-29 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000)),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=200)),
                ('raw_text', models.TextField()),
                ('processed_json', models.JSONField(blank=True, default=dict)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('language', models.CharField(default='unknown', max_length=10)),
                ('classification', models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('RESTRICTED', 'Restricted'), ('CONFIDENTIAL', 'Confidential'), ('SECRET', 'Secret')], default='UNCLASSIFIED', max_length=50)),
                ('priority', models.IntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Medium'), (4, 'Low')], default=3)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending Processing'), ('translating', 'Translating'), ('extracting_entities', 'Extracting Entities'), ('processed', 'Processing Complete'), ('failed', 'Processing Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_count', models.IntegerField(default=0)),
                ('content_length', models.IntegerField(blank=True, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'news_articles_step1',
                'ordering': ['-created_at'],
            },
        ),
    ]
