# Generated by Django 5.2.5 on 2025-09-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='relevance_score',
            field=models.FloatField(default=0.5, help_text='Relevance score (0-1)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='sentiment_score',
            field=models.FloatField(default=0.0, help_text='Sentiment score (-1 to 1)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='translated_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
